program PopularCaptchaTester;

uses
  Vcl.Forms,
  uPopularCaptchaSolver in 'uPopularCaptchaSolver.pas',
  uMainForm in 'uMainForm.pas' {MainForm},
  uWVBrowser in 'source\uWVBrowser.pas',
  uWVWindowParent in 'source\uWVWindowParent.pas',
  uWVTypes in 'source\uWVTypes.pas',
  uWVConstants in 'source\uWVConstants.pas',
  uWVTypeLibrary in 'source\uWVTypeLibrary.pas',
  uWVBrowserBase in 'source\uWVBrowserBase.pas',
  uWVLoader in 'source\uWVLoader.pas',
  uWVWinControl in 'source\uWVWinControl.pas',
  uWVLibFunctions in 'source\uWVLibFunctions.pas',
  uWVInterfaces in 'source\uWVInterfaces.pas',
  uWVCoreWebView2Args in 'source\uWVCoreWebView2Args.pas',
  uWVEvents in 'source\uWVEvents.pas',
  uWVCoreWebView2 in 'source\uWVCoreWebView2.pas',
  uWVCoreWebView2Controller in 'source\uWVCoreWebView2Controller.pas',
  uWVCoreWebView2Environment in 'source\uWVCoreWebView2Environment.pas',
  uWVMiscFunctions in 'source\uWVMiscFunctions.pas',
  uWVCoreWebView2Delegates in 'source\uWVCoreWebView2Delegates.pas',
  uWVLoaderInternal in 'source\uWVLoaderInternal.pas',
  uWVCoreWebView2Settings in 'source\uWVCoreWebView2Settings.pas',
  uWVCoreWebView2Frame in 'source\uWVCoreWebView2Frame.pas',
  uWVCoreWebView2EnvironmentOptions in 'source\uWVCoreWebView2EnvironmentOptions.pas',
  uWVCoreWebView2FrameInfo in 'source\uWVCoreWebView2FrameInfo.pas',
  uWVCoreWebView2FrameInfoCollection in 'source\uWVCoreWebView2FrameInfoCollection.pas',
  uWVCoreWebView2FrameInfoCollectionIterator in 'source\uWVCoreWebView2FrameInfoCollectionIterator.pas',
  uWVCoreWebView2HttpHeadersCollectionIterator in 'source\uWVCoreWebView2HttpHeadersCollectionIterator.pas',
  uWVCoreWebView2HttpRequestHeaders in 'source\uWVCoreWebView2HttpRequestHeaders.pas',
  uWVCoreWebView2HttpResponseHeaders in 'source\uWVCoreWebView2HttpResponseHeaders.pas',
  uWVCoreWebView2WebResourceRequest in 'source\uWVCoreWebView2WebResourceRequest.pas',
  uWVCoreWebView2WebResourceResponse in 'source\uWVCoreWebView2WebResourceResponse.pas',
  uWVCoreWebView2CustomSchemeRegistration in 'source\uWVCoreWebView2CustomSchemeRegistration.pas',
  uWVCoreWebView2BasicAuthenticationResponse in 'source\uWVCoreWebView2BasicAuthenticationResponse.pas',
  uWVCoreWebView2BrowserExtension in 'source\uWVCoreWebView2BrowserExtension.pas',
  uWVCoreWebView2BrowserExtensionList in 'source\uWVCoreWebView2BrowserExtensionList.pas',
  uWVCoreWebView2Certificate in 'source\uWVCoreWebView2Certificate.pas',
  uWVCoreWebView2ClientCertificate in 'source\uWVCoreWebView2ClientCertificate.pas',
  uWVCoreWebView2ClientCertificateCollection in 'source\uWVCoreWebView2ClientCertificateCollection.pas',
  uWVCoreWebView2CompositionController in 'source\uWVCoreWebView2CompositionController.pas',
  uWVCoreWebView2ContextMenuItem in 'source\uWVCoreWebView2ContextMenuItem.pas',
  uWVCoreWebView2ContextMenuItemCollection in 'source\uWVCoreWebView2ContextMenuItemCollection.pas',
  uWVCoreWebView2ContextMenuTarget in 'source\uWVCoreWebView2ContextMenuTarget.pas',
  uWVCoreWebView2ControllerOptions in 'source\uWVCoreWebView2ControllerOptions.pas',
  uWVCoreWebView2Cookie in 'source\uWVCoreWebView2Cookie.pas',
  uWVCoreWebView2CookieList in 'source\uWVCoreWebView2CookieList.pas',
  uWVCoreWebView2CookieManager in 'source\uWVCoreWebView2CookieManager.pas',
  uWVCoreWebView2Deferral in 'source\uWVCoreWebView2Deferral.pas',
  uWVCoreWebView2DownloadOperation in 'source\uWVCoreWebView2DownloadOperation.pas',
  uWVCoreWebView2ExecuteScriptResult in 'source\uWVCoreWebView2ExecuteScriptResult.pas',
  uWVCoreWebView2File in 'source\uWVCoreWebView2File.pas',
  uWVCoreWebView2FileSystemHandle in 'source\uWVCoreWebView2FileSystemHandle.pas',
  uWVCoreWebView2Notification in 'source\uWVCoreWebView2Notification.pas',
  uWVCoreWebView2ObjectCollection in 'source\uWVCoreWebView2ObjectCollection.pas',
  uWVCoreWebView2ObjectCollectionView in 'source\uWVCoreWebView2ObjectCollectionView.pas',
  uWVCoreWebView2PermissionSetting in 'source\uWVCoreWebView2PermissionSetting.pas',
  uWVCoreWebView2PermissionSettingCollectionView in 'source\uWVCoreWebView2PermissionSettingCollectionView.pas',
  uWVCoreWebView2PointerInfo in 'source\uWVCoreWebView2PointerInfo.pas',
  uWVCoreWebView2PrintSettings in 'source\uWVCoreWebView2PrintSettings.pas',
  uWVCoreWebView2ProcessExtendedInfo in 'source\uWVCoreWebView2ProcessExtendedInfo.pas',
  uWVCoreWebView2ProcessExtendedInfoCollection in 'source\uWVCoreWebView2ProcessExtendedInfoCollection.pas',
  uWVCoreWebView2ProcessInfo in 'source\uWVCoreWebView2ProcessInfo.pas',
  uWVCoreWebView2ProcessInfoCollection in 'source\uWVCoreWebView2ProcessInfoCollection.pas',
  uWVCoreWebView2Profile in 'source\uWVCoreWebView2Profile.pas',
  uWVCoreWebView2RegionRectCollectionView in 'source\uWVCoreWebView2RegionRectCollectionView.pas',
  uWVCoreWebView2ScriptException in 'source\uWVCoreWebView2ScriptException.pas',
  uWVCoreWebView2SharedBuffer in 'source\uWVCoreWebView2SharedBuffer.pas',
  uWVCoreWebView2StringCollection in 'source\uWVCoreWebView2StringCollection.pas',
  uWVCoreWebView2WebResourceResponseView in 'source\uWVCoreWebView2WebResourceResponseView.pas',
  uWVCoreWebView2WindowFeatures in 'source\uWVCoreWebView2WindowFeatures.pas',
  uWVFMXBrowser in 'source\uWVFMXBrowser.pas',
  uWVFMXWindowParent in 'source\uWVFMXWindowParent.pas';

{$R *.res}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.CreateForm(TMainForm, MainForm);
  Application.Run;
end.
